"""initial schema (Section 4)

Creates all five tables. The DDL is identical to
backend/migrations/001_initial_schema.sql so the two migration
representations stay in lock-step. Subsequent schema changes (Step 2 onward)
are new autogenerated revisions diffed against the models.

Revision ID: 0001
Revises:
Create Date: 2026-05-17
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SCHEMA_SQL = """
CREATE TABLE sites (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    domain VARCHAR(255) NOT NULL UNIQUE,
    url VARCHAR(500) NOT NULL,
    site_type VARCHAR(50) NOT NULL DEFAULT 'other',
    schedule VARCHAR(50) NOT NULL DEFAULT 'weekly',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    max_pages INTEGER NOT NULL DEFAULT 100,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_audit_at TIMESTAMPTZ,
    metadata JSONB DEFAULT '{}'
);

CREATE TABLE audits (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    site_id UUID NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    triggered_by VARCHAR(50) NOT NULL DEFAULT 'manual',
    score_overall INTEGER,
    score_technical INTEGER,
    score_content INTEGER,
    score_eeeat INTEGER,
    score_performance INTEGER,
    score_structure INTEGER,
    pages_crawled INTEGER DEFAULT 0,
    issues_critical INTEGER DEFAULT 0,
    issues_warning INTEGER DEFAULT 0,
    issues_info INTEGER DEFAULT 0,
    crawl_data JSONB DEFAULT '[]',
    gsc_data JSONB DEFAULT '{}',
    analysis_summary TEXT,
    quick_wins JSONB DEFAULT '[]',
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    error_message TEXT
);

CREATE TABLE audit_issues (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    audit_id UUID NOT NULL REFERENCES audits(id) ON DELETE CASCADE,
    page_url VARCHAR(1000),
    category VARCHAR(100) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    rule_id VARCHAR(100) NOT NULL,
    rule_name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    fix_suggestion TEXT NOT NULL,
    affected_value TEXT,
    expected_value TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_audit_issues_audit_id ON audit_issues(audit_id);
CREATE INDEX idx_audit_issues_severity ON audit_issues(severity);
CREATE INDEX idx_audit_issues_category ON audit_issues(category);

CREATE TABLE api_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    token_prefix VARCHAR(10) NOT NULL,
    scopes JSONB NOT NULL DEFAULT '["audit:read","audit:write","site:read"]',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_used_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE webhooks (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    events JSONB NOT NULL DEFAULT '["audit.complete","audit.failed"]',
    secret VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_triggered_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
"""

DROP_SQL = """
DROP TABLE IF EXISTS audit_issues CASCADE;
DROP TABLE IF EXISTS audits CASCADE;
DROP TABLE IF EXISTS webhooks CASCADE;
DROP TABLE IF EXISTS api_tokens CASCADE;
DROP TABLE IF EXISTS sites CASCADE;
"""


def _run_statements(sql: str) -> None:
    """Execute each `;`-separated statement individually. The asyncpg driver
    rejects multi-statement strings in a single execute, so the schema is
    applied one statement at a time."""
    for statement in sql.split(";"):
        statement = statement.strip()
        if statement:
            op.execute(statement)


def upgrade() -> None:
    _run_statements(SCHEMA_SQL)


def downgrade() -> None:
    _run_statements(DROP_SQL)
